"""Add is_admin column to Attendee with default

Revision ID: bf665e176ab8
Revises: 2f741da94994
Create Date: 2024-08-05 01:02:07.430565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf665e176ab8'
down_revision = '2f741da94994'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendee', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
